---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-leaks-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: open-leaks-secrets
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: litellm
        property: master-key
