"""Gold-layer extraction assets generated by the shared factory.

Bill pipeline: bill_mentions + bill_assertions + bill_embeddings
Member pipeline: member_mentions + member_embeddings (no assertions)
"""

from congress_data.partitions import bill_partitions, member_partitions
from dagster_io.asset_factory import PipelineConfig, extraction_assets

bill_gold_assets = extraction_assets(
    PipelineConfig(
        domain="bill",
        code_location="congress_data",
        chunks_asset_key="bill_chunks",
        group_name="congress",
        partitions_def=bill_partitions,
    )
)

member_gold_assets = extraction_assets(
    PipelineConfig(
        domain="member",
        code_location="congress_data",
        chunks_asset_key="member_chunks",
        group_name="congress",
        partitions_def=member_partitions,
        skip_assertions=True,
    )
)
