"""Gold-layer extraction assets generated by the shared factory.

Replaces manually-defined leak_mentions, leak_assertions, leak_embeddings
with a single extract_validated() call via @multi_asset + embeddings @asset.
"""

from dagster_io.asset_factory import PipelineConfig, extraction_assets

leak_gold_assets = extraction_assets(
    PipelineConfig(
        domain="leak",
        code_location="open_leaks",
        chunks_asset_key="leak_chunks",
        group_name="leaks",
    )
)
