#!/usr/bin/env bash
# Pull dev secrets from the catalyst-cluster k8s namespaces and write to local
# .envrc files for direnv. Idempotent — re-run any time the cluster secrets
# rotate. Values are never echoed to stdout.
#
# Writes:
#   .envrc.cluster                                — shared API keys + IO config
#   packages/media-ingest/.envrc                  — domain-specific defaults
#   packages/congress-data/.envrc                 — domain-specific defaults
#   packages/open-leaks/.envrc                    — domain-specific defaults
#
# Each .envrc starts with `source_env ../../.envrc.cluster` so domain shells
# inherit the shared keys. After running, add to your top-level .envrc:
#
#   source_env_if_exists .envrc.cluster
#
# and ``direnv allow``.

set -euo pipefail

cd "$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"

CTX="${KUBE_CONTEXT:-admin@catalyst-cluster}"
NS_DATA="catalyst-data"

if ! kubectl --context="$CTX" get ns "$NS_DATA" >/dev/null 2>&1; then
    echo "error: cannot reach k8s context $CTX namespace $NS_DATA" >&2
    exit 1
fi

# Read a key from a k8s secret, base64-decoded. Suppresses output on missing.
sec() {
    local secret="$1" key="$2"
    kubectl --context="$CTX" -n "$NS_DATA" get secret "$secret" \
        -o jsonpath="{.data.$key}" 2>/dev/null | base64 -d
}

# Read inline env value from a deployment (non-secret defaults like LLM_BASE_URL).
deploy_env() {
    local deploy="$1" key="$2" json
    json=$(kubectl --context="$CTX" -n "$NS_DATA" get deploy "$deploy" -o json 2>/dev/null) || return 0
    [[ -z "$json" ]] && return 0
    printf '%s' "$json" | python3 -c "
import json, sys
d = json.load(sys.stdin)
for c in d['spec']['template']['spec']['containers']:
    for e in c.get('env', []):
        if e['name'] == '$key' and 'value' in e:
            print(e['value'])
            sys.exit(0)
" 2>/dev/null || true
}

# ── Shared cluster secrets ─────────────────────────────────────────────────

echo "Writing .envrc.cluster …"
{
    echo "# Auto-generated by scripts/ops/pull-dev-secrets.sh — DO NOT COMMIT"
    echo "# Re-run the script to refresh. Sourced by per-domain .envrc files."
    echo ""
    echo "export HF_TOKEN=$(sec hf-credentials HF_TOKEN)"
    echo "export LLM_API_KEY=$(sec llm-credentials LLM_API_KEY)"
    echo "export OPENAI_API_KEY=$(sec llm-credentials LLM_API_KEY)  # litellm proxy uses LLM_API_KEY for OpenAI compat"
    echo "export CONGRESS_API_KEY=$(sec congress-data-secrets CONGRESS_API_KEY)"
    echo ""
    echo "# MinIO/S3 (prod cluster). Local-dev integration tests use LocalJsonIOManager"
    echo "# (DAGSTER_IO_BACKEND=local — see Taskfile task dev). These vars are only used"
    echo "# by code paths that hit the prod cluster."
    echo "export DAGSTER_S3_ENDPOINT_URL=$(sec dagster-s3-credentials DAGSTER_S3_ENDPOINT_URL)"
    echo "export DAGSTER_S3_ACCESS_KEY=$(sec dagster-s3-credentials DAGSTER_S3_ACCESS_KEY)"
    echo "export DAGSTER_S3_SECRET_KEY=$(sec dagster-s3-credentials DAGSTER_S3_SECRET_KEY)"
    echo "export DAGSTER_S3_BUCKET=$(sec dagster-s3-credentials DAGSTER_S3_BUCKET)"
    echo ""
    echo "# OTEL silenced for local-dev — alloy.monitoring.svc.cluster.local is in-cluster only."
    echo "export OTEL_METRICS_EXPORTER=none"
    echo "export OTEL_TRACES_EXPORTER=none"
} > .envrc.cluster
chmod 600 .envrc.cluster

# ── Domain-specific .envrc files ───────────────────────────────────────────

write_domain_envrc() {
    local domain_dir="$1" code_loc="$2" deploy_name="$3" llm_model_default="$4"
    local llm_base_url llm_model embedding_base_url embedding_model

    llm_base_url=$(deploy_env "$deploy_name" LLM_BASE_URL || true)
    llm_model=$(deploy_env "$deploy_name" LLM_MODEL || true)
    embedding_base_url=$(deploy_env "$deploy_name" EMBEDDING_BASE_URL || true)
    embedding_model=$(deploy_env "$deploy_name" EMBEDDING_MODEL || true)

    [[ -z "$llm_model" ]] && llm_model="$llm_model_default"

    echo "Writing $domain_dir/.envrc …"
    {
        echo "# Auto-generated by scripts/ops/pull-dev-secrets.sh — DO NOT COMMIT"
        echo "# Inherits shared keys from repo-root .envrc.cluster."
        echo "source_env ../../.envrc.cluster"
        echo ""
        echo "export DAGSTER_CODE_LOCATION=$code_loc"
        [[ -n "$llm_base_url" ]] && echo "export LLM_BASE_URL=$llm_base_url"
        [[ -n "$llm_model" ]] && echo "export LLM_MODEL=$llm_model"
        [[ -n "$embedding_base_url" ]] && echo "export EMBEDDING_BASE_URL=$embedding_base_url"
        [[ -n "$embedding_model" ]] && echo "export EMBEDDING_MODEL=$embedding_model"
    } > "$domain_dir/.envrc"
    chmod 600 "$domain_dir/.envrc"
}

write_domain_envrc packages/media-ingest media_ingest media-ingest "runpod/gemma-4-31b-it"
write_domain_envrc packages/congress-data congress_data congress-data "runpod/gemma-4-31b-it"
write_domain_envrc packages/open-leaks open_leaks open-leaks "runpod/gemma-4-31b-it"

echo ""
echo "Done. Next steps:"
echo "  1. Add 'source_env_if_exists .envrc.cluster' to your top-level .envrc (if not already)."
echo "  2. cd into each domain dir and run 'direnv allow' to enable per-domain envs."
echo "  3. .envrc.cluster and packages/*/.envrc are gitignored — verify with 'git status'."
