---
apiVersion: v1
kind: Service
metadata:
  name: open-leaks
  labels:
    app: open-leaks
    app.kubernetes.io/name: open-leaks
    app.kubernetes.io/part-of: dagster
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 4000
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: open-leaks
