---
apiVersion: v1
kind: Service
metadata:
  name: knowledge-graph-api
  labels:
    app: knowledge-graph-api
    app.kubernetes.io/name: knowledge-graph-api
    app.kubernetes.io/part-of: catalyst-data
spec:
  selector:
    app: knowledge-graph-api
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
