---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: congress-data-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: congress-data-secrets
    creationPolicy: Owner
  data:
    - secretKey: CONGRESS_API_KEY
      remoteRef:
        key: congress-data-secrets
        property: CONGRESS_API_KEY
