---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: hf-credentials
    creationPolicy: Owner
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: huggingface_runpod_key
        property: password
