---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dagster-code-locations
  namespace: catalyst-data
  labels:
    app.kubernetes.io/part-of: dagster
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dagster
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
