"""Gold-layer extraction assets generated by the shared factory.

Replaces manually-defined media_mentions, media_assertions, media_embeddings
with a single extract_validated() call via @multi_asset + embeddings @asset.
"""

from dagster_io.asset_factory import PipelineConfig, extraction_assets
from media_ingest.partitions import media_partitions

media_gold_assets = extraction_assets(
    PipelineConfig(
        domain="media",
        code_location="media_ingest",
        chunks_asset_key="media_chunks",
        group_name="media_ingest",
        partitions_def=media_partitions,
    )
)
