---
apiVersion: v1
kind: Service
metadata:
  name: knowledge-graph
  labels:
    app: knowledge-graph
    app.kubernetes.io/name: knowledge-graph
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 4000
      targetPort: grpc
      protocol: TCP
  selector:
    app: knowledge-graph
